# Generated by Django 5.0.1 on 2024-02-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_breakdown_exam_questions_exammodule_exam_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
